version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: hosxp_dashboard-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}
    # restart: always
    networks:
      - dashboard-net
    expose:
      - 9090
  node-exporter:
    image: prom/node-exporter:latest
    container_name: hosxp_dashboard-node-exporter
    networks:
      - dashboard-net
    # restart: always
  grafana:
    image: grafana/grafana:latest 
    container_name: hosxp_dashboard-grafana   
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana_data:/var/lib/grafana 
      # - ./grafana-config:/etc/grafana
      - ./grafana-config/grafana_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:rw
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    # restart: always
    networks:
      - dashboard-net


networks:
  dashboard-net:
    driver: bridge
